//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManifestUpdater.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManifestUpdater.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;Auto Mount&quot;,
        ///    &quot;Author&quot;: &quot;zepheon&quot;,
        ///    &quot;Id&quot;: {
        ///      &quot;Id&quot;: &quot;AutoMount&quot;,
        ///      &quot;Type&quot;: &quot;UMM&quot;
        ///    },
        ///    &quot;Service&quot;: {
        ///      &quot;GitHub&quot;: {
        ///        &quot;Owner&quot;: &quot;zephe0n&quot;,
        ///        &quot;RepoName&quot;: &quot;AutoMount&quot;,
        ///        &quot;ReleaseFilter&quot;: null
        ///      },
        ///      &quot;Nexus&quot;: null
        ///    },
        ///    &quot;Version&quot;: {
        ///      &quot;Latest&quot;: {
        ///        &quot;Version&quot;: &quot;0.1.0&quot;,
        ///        &quot;Url&quot;: &quot;https://github.com/zephe0n/AutoMount/releases/download/v0.1.0/AutoMount-v0.1.0.zip&quot;,
        ///        &quot;Changelog&quot;: &quot;&quot;
        ///      },
        ///      &quot;Ver [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Generated_Manifest {
            get {
                return ResourceManager.GetString("Generated_Manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  // Please keep sorted by Name.
        ///
        ///  {
        ///    &quot;Name&quot;: &quot;Auto Mount&quot;,
        ///    &quot;Author&quot;: &quot;zepheon&quot;,
        ///    &quot;Id&quot;: {
        ///      &quot;Id&quot;: &quot;AutoMount&quot;,
        ///      &quot;Type&quot;: &quot;UMM&quot;
        ///    },
        ///    &quot;Service&quot;: {
        ///      &quot;GitHub&quot;: {
        ///        &quot;Owner&quot;: &quot;zephe0n&quot;,
        ///        &quot;RepoName&quot;: &quot;AutoMount&quot;
        ///      }
        ///    },
        ///    &quot;HomepageUrl&quot;: &quot;https://github.com/zephe0n/AutoMount&quot;,
        ///    &quot;Tags&quot;: [ &quot;UserInterface&quot; ]
        ///  },
        ///  
        ///  {
        ///    &quot;Name&quot;: &quot;Bubble Buffs&quot;,
        ///    &quot;Author&quot;: &quot;Bubbles&quot;,
        ///    &quot;Id&quot;: {
        ///      &quot;Id&quot;: &quot;BubbleBuffs&quot;,
        ///      &quot;Type&quot;: &quot;UMM&quot;
        ///    }, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string internal_manifest {
            get {
                return ResourceManager.GetString("internal_manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;GeneratedManifestUrl&quot;: &quot;https://raw.githubusercontent.com/Pathfinder-WOTR-Modding-Community/ModFinder/main/ManifestUpdater/Resources/generated_manifest.json&quot;,
        ///  &quot;ExternalManifestUrls&quot;: [ ]
        ///}.
        /// </summary>
        internal static string Master_Manifest {
            get {
                return ResourceManager.GetString("Master_Manifest", resourceCulture);
            }
        }
    }
}
